version: "3.8"

services:
  postgres:
    container_name: go-sample-postgres
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: snippets
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  go-sample:
    container_name: go-sample-server
    restart: always
    build:
      context: .
    depends_on:
      - postgres
    environment:
      LISTEN: ":4040"
      DATABASE_DSN: "postgresql://postgres:docker@postgres:5432/snippets?sslmode=disable"
      API_TOKEN: ""
    command: [ "server" ]
    ports:
      - 4040:4040

volumes:
  postgres-data: { }
