name: pr:golang-tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false
      - name: lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Run tests
        run: task test

# TODO: Enable coverage
#  coverage:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 2
#      - uses: actions/setup-go@v5
#        with:
#          go-version: '1.22'
#      - name: Install Task
#        uses: arduino/setup-task@v2
#        with:
#          version: 3.x
#      - name: Run coverage
#        run: task coverage
#      - name: Upload coverage to Codecov
#        run: bash <(curl -s https://codecov.io/bash)
