---
name: "tag:release"
on:
  push:
    # TODO: delete after debug
    branches:
      - '**'
    tags:
      - v*

jobs:
  docker-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare docker tags
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=
            type=ref,event=branch
            type=semver,pattern={{version}},prefix=v

      # Prepare outputs for build-args
      - name: Set outputs
        id: vars
        # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        run: |
          VERSION="$(git describe --tags --always 2>/dev/null)"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # This is a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.meta.outputs.tags }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
          build-args: |
            GITHUB_REPOSITORY=${{ github.repository }}
            GIT_BRANCH=${{ github.ref_name }}
            GIT_COMMIT_SHA=${{ steps.vars.outputs.sha_short }}
            VERSION=${{ steps.vars.outputs.version }}
